[package]
authors = ["Hugo Adamove", "Peter Jaško"]
name = "pv021_project"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75" # Error handling
rand = "0.8.5"    # Random number generator
